version: '3'

services:
  db:
    image: mysql:5.7
    container_name: meish_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - datavol:/var/lib/mysql
  back:
    build: back/
    container_name: meish_back
    environment:
      - BUNDLE_PATH=/bundle
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./back:/app
      - ./back/vendor/bundle:/app/vendor/bundle
      - bundle_path:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
  front:
    build: front/
    container_name: meish_front
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_DOMAIN=$REACT_APP_BACKEND_DOMAIN
    command: [npm, run, start]
    ports:
      - 8080:8080
    volumes:
      - ./front:/app
      - /app/node_modules
volumes:
  bundle_path:
  datavol:
