version: '3'

services:
  db:
    image: mysql:5.7
    container_name: meish_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - datavol:/var/lib/mysql
  web:
    build: web/
    container_name: meish_back
    environment:
      - BUNDLE_PATH=/bundle
      - TWITTER_KEY=$TWITTER_KEY
      - TWITTER_SECRET=$TWITTER_SECRET
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_HOST=db
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./web:/app
      - ./web/vendor/bundle:/app/vendor/bundle
      - bundle_path:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  bundle_path:
  datavol:
