[build]
  base = "frontend/"
  publish = "dist"

[context.production]
  command = "yarn && yarn build:production"

[context.staging]
  command = "yarn && yarn build:development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
