
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { root } %>
  password: <%= ENV.fetch("DB_PASSWORD") { password } %>
  host: <%= ENV.fetch("DB_HOST") { db } %>

development:
  <<: *default
  database: back_development

test:
  <<: *default
  database: back_test

production:
  <<: *default
  database: back_production
