
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { root } %>
  password: <%= ENV.fetch("DB_PASSWORD") { password } %>
  host: <%= ENV.fetch("DB_HOST") { localhost } %>

development:
  <<: *default
  database: meish_development

test:
  <<: *default
  database: meish_test

production:
  <<: *default
  database: meish_production
