default: &default
  front:
    auth_callback_url:
      twitter: 'http://localhost:8080/cards'

development:
  <<: *default

test:
  <<: *default

production:
  front:
    auth_callback_url:
      twitter: <%= ENV.fetch("CALLBACK_URL") { 'http://localhost:8080/cards' } %>
