name: CI

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install, build
        run: |
          yarn install --frozen-lockfile
          yarn build
        working-directory: ./front
  run_front_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm run tests
        run: |
          npm run tests
        working-directory: ./front
  run_back_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use ruby ${{ matrix.ruby }}
        uses: actions/setup-node@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test with Rake
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails test
      - name: Run tests
        run: |
          bundle exec rspec --color
        working-directory: ./back
